* Tema 5
   * [Actividad 1: Introducción y arquitectura de FileZilla Server](https://github.com/AngelCSR/Portfolio/blob/main/Tema%205/Ejercicios/Actividad1_Introducci%C3%B3n_y_arquitectura_FileZilla%20Server.md)
   * [Actividad 2: Instalación y configuración inicial del servidor](https://github.com/AngelCSR/Portfolio/blob/main/Tema%205/Ejercicios/Actividad2-Instalaci%C3%B3n-y-configuraci%C3%B3n-inicial-del-servidor.md)
   * [Actividad 3: Creación de usuarios y grupos](https://github.com/AngelCSR/Portfolio/blob/main/Tema%205/Ejercicios/Actividad3_Usuarios_y_Grupos.md)
   * [Actividad 4: Configuración de acceso anónimo](https://github.com/AngelCSR/Portfolio/blob/main/Tema%205/Ejercicios/actividad4_Configuraci%C3%B3n_de_acceso_an%C3%B3nimo.md)
   * [Actividad 5: Pruebas en modo activo y pasivo](https://github.com/AngelCSR/Portfolio/blob/main/Tema%205/Ejercicios/actividad5.md)
   * [Actividad 6: Pruebas con clientes en línea de comandos](https://github.com/AngelCSR/Portfolio/blob/main/Tema%205/Ejercicios/actividad_6_ftp_cli.md)
   * [Actividad 7: Pruebas con clientes gráficos](https://github.com/AngelCSR/Portfolio/blob/main/Tema%205/Ejercicios/Actividad-7practica_filezilla_sftp.md)
   * [Actividad 8: Configuración de FTP seguro (FTPS)](https://github.com/AngelCSR/Portfolio/blob/main/Tema%205/Ejercicios/actividad_8_ftps.md)
   * [Actividad 9: Uso del navegador como cliente FTP](https://github.com/AngelCSR/Portfolio/blob/main/Tema%205/Ejercicios/actividad_9_navegador_ftp.md)
   * [Actividad 10: Integración de FTP con servidor web](https://github.com/AngelCSR/Portfolio/blob/main/Tema%205/Ejercicios/actividad10-ftp_publicacion_web.md)
   * [Actividad 11: Disponibilidad y buenas prácticas](https://github.com/AngelCSR/Portfolio/blob/main/Tema%205/Ejercicios/actividad_11_disponibilidad_practicas.md)
   * [Actividad 12: Documentación](https://github.com/AngelCSR/Portfolio/blob/main/Tema%205/Ejercicios/filezilla_ftp_documentation.md)
